serve:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange:
      producer: ex.producer.spring
    routing-key:
      producer: rk.producer.spring
    deadletter:
      producer: dl.producer.spring